title: Studying Android Studio/IntelliJ Internals
description: How to debug the IDE!
theme: just-the-docs

url: https://rogerhu.github.io/studying-android-studio-internals

aux_links:
  Template Repository: https://rogerhu.github.io/studying-android-studio-internals
