title: Studying Android Studio/IntelliJ Internals
description: How to debug the IDE!
theme: just-the-docs
color_scheme: android

url: https://rogerhu.github.io/studying-android-studio-internals

aux_links:
  Template Repository: https://github.com/rogerhu/studying-android-studio-internals
